package Main;

import CantoniLib.*;

public class Main {
        public static void main(String[] args) {
                do{
                        for(int i=(int)'0'; i<=(int)'z'+10; i++)
                                System.out.println((char)i + "   " + i);
                        System.out.println("\n");
                }while(1==2);
                
                System.out.println("Byte: " + Rand.newByte((byte)0, (byte)1));
                System.out.println("Short: " + Rand.newShort((short)0, (short)1));
                System.out.println("Int: " + Rand.newInt(0, 5));
                System.out.println("Long: " + Rand.newLong(0, 7));
                System.out.println("Float: " + Rand.newFloat(0, 5.5f));
                System.out.println("Double: " + Rand.newDouble(0,3.3));
                System.out.println("Char: " + Rand.newChar('a', 'z'));
                System.out.println("Boolean: " + Rand.newBoolean());
                System.out.println();
                
                System.out.println("Letters lowercase: " + Rand.newStringLetters(10, false));
                System.out.println("Letters uppercase: " + Rand.newStringLetters(10, true));
                System.out.println("Numbers: " + Rand.newStringNumbers(10));
                System.out.println("Alphanumerical lowercase: " + Rand.newStringAlphanumerical(10, false));
                System.out.println("Alphanumerical uppercase: " + Rand.newStringAlphanumerical(10, true));
                System.out.println("Letters mixed: " + Rand.newStringLettersMixed(10));
                System.out.println("Alphanumerical mixed: " + Rand.newStringAlphanumericalMixed(10));
                System.out.println();
                
                for(int i=0; i<10; i++)
                        System.out.println("Chance 30%: " + Rand.chance(0.3));
                System.out.println();
                
                System.out.println("d4: " + Rand.d4());
                System.out.println("d6: " + Rand.d6());
                System.out.println("d8: " + Rand.d8());
                System.out.println("d10: " + Rand.d10());
                System.out.println("d12: " + Rand.d12());
                System.out.println("d20: " + Rand.d20());
                System.out.println("d50: " + Rand.d50());
                System.out.println("d100: " + Rand.d100());
                System.out.println();
                
                byte[] bArr = new byte[5];
                short[] sArr = new short[5];
                int[] iArr = new int[5];
                long[] lArr = new long[5];
                float[] fArr = new float[5];
                double[] dArr = new double[5];
                char[] cArr = new char[5];
                boolean[] boolArr = new boolean[5];
                
                Vet.fill(bArr, (byte)1);
                Vet.fill(sArr, (short)2);
                Vet.fill(iArr, 5);
                Vet.fill(lArr, 10);
                Vet.fill(fArr, 3.4f);
                Vet.fill(dArr, 7.5);
                Vet.fill(cArr, 'N');
                Vet.fill(boolArr, true);
                
                System.out.println("ARRAYS:");
                do{ // Cycle to use temporary variables
                        int[] v = null;
                        System.out.print("NULL: ");
                        Vet.print(v);
                        System.out.print("\nEMPTY: ");
                        Vet.print(new int[0]);
                        System.out.println();
                        System.out.println();
                }while(1==2);
                Vet.print(bArr);
                System.out.println();
                Vet.print(sArr);
                System.out.println();
                Vet.print(iArr);
                System.out.println();
                Vet.print(lArr);
                System.out.println();
                Vet.print(fArr);
                System.out.println();
                Vet.print(dArr);
                System.out.println();
                Vet.print(cArr);
                System.out.println();
                Vet.print(boolArr);
                System.out.println();
                do{
                        char[] c = new char[50];
                        System.out.print("Fill letters: ");
                        Vet.fillLetters(c);
                        Vet.print(c);
                        System.out.println();
                        System.out.print("Fill letters: ");
                        Vet.sort(c);
                        Vet.print(c);
                        System.out.println();
                        System.out.print("Fill letters (upperCase): ");
                        Vet.fillLetters(c,true);
                        Vet.print(c);
                        System.out.println();
                        System.out.print("Fill letters (upperCase): ");
                        Vet.sort(c);
                        Vet.print(c);
                        System.out.println();
                        System.out.print("Fill letters (lowerCase): ");
                        Vet.fillLetters(c, false);
                        Vet.print(c);
                        System.out.println();
                        System.out.print("Fill letters (lowerCase): ");
                        Vet.sort(c);
                        Vet.print(c);
                        System.out.println();
                        System.out.print("Fill number: ");
                        Vet.fillNumbers(c);
                        Vet.print(c);
                        System.out.println();
                        System.out.print("Fill number: ");
                        Vet.sort(c);
                        Vet.print(c);
                        System.out.println();
                        System.out.print("Fill alphanumerical: ");
                        Vet.fillAlphanumerical(c);
                        Vet.print(c);
                        System.out.println();
                        System.out.print("Fill alphanumerical: ");
                        Vet.sort(c);
                        Vet.print(c);
                        System.out.println();
                        System.out.print("Fill alphanumerical (upperCase): ");
                        Vet.fillAlphanumerical(c,true);
                        Vet.print(c);
                        System.out.println();
                        System.out.print("Fill alphanumerical (upperCase): ");
                        Vet.sort(c);
                        Vet.print(c);
                        System.out.println();
                        System.out.print("Fill alphanumerical (lowerCase): ");
                        Vet.fillAlphanumerical(c,false);
                        Vet.print(c);
                        System.out.println();
                        System.out.print("Fill alphanumerical (lowerCase): ");
                        Vet.sort(c);
                        Vet.print(c);
                        System.out.println();
                }while(1==2);
                System.out.println();
                System.out.println("------------------------------------------");
                System.out.println();
                
                Vet.fillRandom(bArr, (byte)0, (byte)3);
                Vet.fillRandom(sArr, (short)2,  (short)7);
                Vet.fillRandom(iArr, 5,10);
                Vet.fillRandom(lArr, 10,20);
                Vet.fillRandom(fArr, 3.4f,5.76f);
                Vet.fillRandom(dArr, 7.5,10.345);
                Vet.fillRandom(cArr, 'N','s');
                Vet.fillRandom(boolArr);
                
                System.out.println("SEPARATION / WIDTH TESTS:");
                System.out.println();
                Vet.print(bArr,4," || ");
                System.out.println();
                Vet.print(sArr, 5,"\n");
                System.out.println();
                Vet.print(iArr,8," -- ");
                System.out.println();
                Vet.print(lArr,10," / ");
                System.out.println();
                Vet.print(fArr,3,",\n");
                System.out.println();
                Vet.print(dArr,9,"__\n");
                System.out.println();
                Vet.print(cArr,2,"; ");
                System.out.println();
                Vet.print(boolArr,"\t");
                System.out.println();
                System.out.println();
                System.out.println("------------------------------------------");
                System.out.println();
                
                bArr[2] = (byte) 4;
                sArr[3] = (short) 1;
                iArr[0] = 70;
                lArr[4] = 60;
                fArr[4] = 7.56f;
                dArr[1] = 0.034;
                
                System.out.println("FIND:\n");
                Vet.print(bArr);
                System.out.println("\nFIND 4 (pos: 2) --> " + Vet.find(bArr, (byte) 4, false));
                System.out.println();
                Vet.print(sArr);
                System.out.println("\nFIND 1 (pos: 3) --> " + Vet.find(sArr, (short) 1, false));
                System.out.println();
                Vet.print(iArr);
                System.out.println("\nFIND 70 (pos: 0) --> " + Vet.find(iArr, 70, false));
                System.out.println();
                Vet.print(lArr);
                System.out.println("\nFIND 60 (pos: 4) --> " + Vet.find(lArr, 60, false));
                System.out.println();
                Vet.print(fArr,2);
                System.out.println("\nFIND 7.56 (pos: 4) --> " + Vet.find(fArr, 7.56f, false));
                System.out.println();
                Vet.print(dArr,3);
                System.out.println("\nFIND 0.034 (pos: 1) --> " + Vet.find(dArr, 0.034, false));
                System.out.println();
                Vet.print(cArr);
                System.out.println("\nFIND 'A' (pos: XX) --> " + Vet.find(cArr, 'A', false));
                System.out.println();
                Vet.print(boolArr);
                System.out.print("\nFIND false (pos: ???) --> " + Vet.find(boolArr, false, false));
                System.out.print("\nFIND false (findAll) --> ");
                Vet.print(Vet.findAll(boolArr, false));
                System.out.println();
                System.out.println();
                System.out.println("------------------------------------------");
                System.out.println();
                
                Vet.sort(bArr);
                Vet.sort(sArr);
                Vet.sort(iArr);
                Vet.sort(lArr);
                Vet.sort(fArr);
                Vet.sort(dArr);
                Vet.sort(cArr);
                Vet.sort(boolArr);
                
                System.out.println("FIND (sorted):\n");
                Vet.print(bArr);
                System.out.print("\nFIND 4 --> " + Vet.find(bArr, (byte) 4, true));
                System.out.println("\nFIND 4 (binarySearch) --> " + Vet.binarySearch(bArr, (byte) 4));
                System.out.println();
                Vet.print(sArr);
                System.out.print("\nFIND 1 --> " + Vet.find(sArr, (short) 1, true));
                System.out.println("\nFIND 1 (binarySearch) --> " + Vet.binarySearch(sArr, (short) 1));
                System.out.println();
                Vet.print(iArr);
                System.out.print("\nFIND 70 --> " + Vet.find(iArr, 70, true));
                System.out.println("\nFIND 70 (binarySearch) --> " + Vet.binarySearch(iArr, 70));
                System.out.println();
                Vet.print(lArr);
                System.out.print("\nFIND 60 --> " + Vet.find(lArr, 60, true));
                System.out.println("\nFIND 60 (binarySearch) --> " + Vet.binarySearch(lArr, 60));
                System.out.println();
                Vet.print(fArr,2);
                System.out.print("\nFIND 7.56 --> " + Vet.find(fArr, 7.56f, true));
                System.out.println("\nFIND 7.56 (binarySearch) --> " + Vet.binarySearch(fArr, 7.56f));
                System.out.println();
                Vet.print(dArr,3);
                System.out.print("\nFIND 0.034 --> " + Vet.find(dArr, 0.034, true));
                System.out.println("\nFIND 0.034 (binarySearch) --> " + Vet.binarySearch(dArr, 0.034));
                System.out.println();
                Vet.print(cArr);
                System.out.print("\nFIND 'a' --> " + Vet.find(cArr, 'a', true));
                System.out.println("\nFIND 'a' (binarySearch) --> " + Vet.binarySearch(cArr, 'a'));
                System.out.println();
                Vet.print(boolArr);
                System.out.print("\nFIND false --> " + Vet.find(boolArr, false, true));
                System.out.print("\nFIND false (binarySearch) --> " + Vet.binarySearch(boolArr, false));
                System.out.print("\nFIND false (findAll) --> ");
                Vet.print(Vet.findAll(boolArr, false)); 
                System.out.println();
                System.out.println();
                System.out.println("------------------------------------------");
                System.out.println();
                
                Vet.print(bArr);
                System.out.println();
                Vet.replace(bArr, (byte) 4, (byte) 5);
                Vet.print(bArr);
                System.out.println("\nREPLACED 4 --> 5\n");
                Vet.print(sArr);
                System.out.println();
                Vet.replace(sArr, (short) 1, (short) 6);
                Vet.print(sArr);
                System.out.println("\nREPLACED 1 --> 6\n");
                Vet.print(iArr);
                System.out.println();
                Vet.replace(iArr,  70, 11);
                Vet.print(iArr);
                System.out.println("\nREPLACED 70 --> 11\n");
                Vet.print(lArr);
                System.out.println();
                Vet.replace(lArr,  60, 11);
                Vet.print(lArr);
                System.out.println("\nREPLACED 60 --> 11\n");
                Vet.print(fArr,2);
                System.out.println();
                Vet.replace(fArr,  7.56f, 11.23f);
                Vet.print(fArr,2);
                System.out.println("\nREPLACED 7.56 --> 11.23\n");
                Vet.print(dArr,3);
                System.out.println();
                Vet.replace(dArr,  0.034, 20.3);
                Vet.print(dArr,3);
                System.out.println("\nREPLACED 0.034 --> 20.3\n");
                Vet.print(cArr);
                System.out.println();
                Vet.replace(cArr,  'b', 'z');
                Vet.print(cArr);
                System.out.println("\nREPLACED 'b' --> 'z'\n");
                Vet.print(boolArr);
                System.out.println();
                Vet.replace(boolArr,  false, true);
                Vet.print(boolArr);
                System.out.println("\nREPLACED false --> true\n");
                
                do{
                        int[] test1 = {0,1,2,1,0};
                        Vet.print(test1);
                        System.out.println();
                        
                        int[] v = {0,1}, nV = {5,6};
                        Vet.replaceMult(test1, v, nV);
                        
                        Vet.print(test1);
                        System.out.println("\nREPLACED 0,1 --> 5,6\n");
                }
                while(true!=true);
                Vet.fillRandom(boolArr);
                System.out.println("------------------------------------------");
                System.out.println();
                
                System.out.println("SHUFFLES:\n");
                Vet.print(bArr);
                System.out.println();
                Vet.shuffle(bArr);
                Vet.print(bArr);
                System.out.println();
                System.out.println();
                Vet.print(sArr);
                System.out.println();
                Vet.shuffle(sArr);
                Vet.print(sArr);
                System.out.println();
                System.out.println();
                Vet.print(iArr);
                System.out.println();
                Vet.shuffle(iArr,30);
                Vet.print(iArr);
                System.out.println("\n30 ITERATIONS");
                System.out.println();
                Vet.print(lArr);
                System.out.println();
                Vet.shuffle(lArr,1);
                Vet.print(lArr);
                System.out.println("\n1 ITERATION");
                System.out.println();
                Vet.print(fArr,2);
                System.out.println();
                Vet.shuffle(fArr,60);
                Vet.print(fArr,2);
                System.out.println("\n60 ITERATIONS");
                System.out.println();
                Vet.print(dArr,3);
                System.out.println();
                Vet.shuffle(dArr,0);
                Vet.print(dArr,3);
                System.out.println("\n0 ITERATIONS");
                System.out.println();
                Vet.print(cArr);
                System.out.println();
                Vet.shuffle(cArr);
                Vet.print(cArr);
                System.out.println();
                System.out.println();
                Vet.print(boolArr);
                System.out.println();
                Vet.shuffle(boolArr);
                Vet.print(boolArr);
                System.out.println();
                System.out.println();
                System.out.println("------------------------------------------");
                System.out.println();
                
                System.out.println("PICK RANDOM:\n");
                Vet.print(bArr);
                System.out.println("\nPicked: " + Vet.pickRandom(bArr));
                System.out.println();
                Vet.print(sArr);
                System.out.println("\nPicked: " + Vet.pickRandom(sArr));
                System.out.println();
                Vet.print(iArr);
                System.out.println("\nPicked: " + Vet.pickRandom(iArr));
                System.out.println();
                Vet.print(lArr);
                System.out.println("\nPicked: " + Vet.pickRandom(lArr));
                System.out.println();
                Vet.print(fArr,2);
                System.out.println("\nPicked: " + Vet.pickRandom(fArr));
                System.out.println();
                Vet.print(dArr,3);
                System.out.println("\nPicked: " + Vet.pickRandom(dArr));
                System.out.println();
                Vet.print(cArr);
                System.out.println("\nPicked: " + Vet.pickRandom(cArr));
                System.out.println();
                Vet.print(boolArr);
                System.out.println("\nPicked: " + Vet.pickRandom(boolArr));
                System.out.println();
                System.out.println("------------------------------------------");
                System.out.println();
        }
        
}